name: Checks

on:
  push:
    branches:
      - "*.x"
  pull_request:

jobs:
  roave-bc-check:
    name: Roave BC Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Roave BC Check
        uses: "docker://nyholm/roave-bc-check-ga"
